#!/bin/sh
set -x
set -e

# ensure everything is available
agshoes-present
agshoes-config-present

# update data
agshoes-mail-sync || true
agshoes-vdir-sync

# update archives
agshoes-local-sync
agshoes-remote-sync
