#!/bin/sh

cd "$HOME"

rsync \
    --partial \
    --progress \
    --archive \
    --del \
    --delete-excluded \
    --verbose \
    --cvs-exclude \
    --exclude-from .backupexclude \
    . \
    /opt/archive
