#!/bin/sh
# TODO: implement with maid or ansible

# remove homebrew
brew cleanup
brew cask list | xargs -L1 -t brew cask uninstall || true
brew list | xargs -L1 -t brew uninstall --force
brew prune

# cd `brew --prefix`
# git ls-files | xargs -0 rm
# rm -rf Cellar
# rm -r Library/Homebrew Library/Aliases Library/Formula Library/Contributions
# test -d Library/LinkedKegs && rm -r Library/LinkedKegs
# rmdir -p bin Library share/man/man1 2> /dev/null
# rm -rf .git
# rm -rf ~/Library/Caches/Homebrew
# rm -rf ~/Library/Logs/Homebrew
# rm -rf /Library/Caches/Homebrew

# remove ruby-install'd rubies
# rm -rf /opt/rubies

if [ -L $HOME/.bin ]; then
    rm $HOME/.bin
fi

if [ -L $HOME/Documents ]; then
    rm $HOME/Documents
fi

if [ -L $HOME/Pictures ]; then
    rm $HOME/Pictures
fi

if [ -L $HOME/src ]; then
    rm $HOME/src
fi
