#!/usr/bin/env ruby -w
# TODO: rewrite in curl + jq
require 'rest-client'
require 'json'
require 'pp'

ARGV.each do |word|
  resp = RestClient.get("http://domai.nr/api/json/search?q=#{word}")
  data = JSON.parse(resp)
  domains = data['results'].
    select do |domain|
      domain['availability'] != "taken" and
      domain['availability'] != "unavailable" and
      domain['availability'] != "tld"
    end.
    each do |domain|
      puts 'http://%s%s: %s' % [domain['domain'], domain['path'], domain['availability']]
    end
end
