#!/bin/sh
# If you have previously run this script, you must manually remove the the line that was created.
# in /etc/racoon/racoon.conf remove the second to last line of the script. include "/etc/racoon/remote/*.conf"

mkdir /etc/racoon/remote
cp /var/run/racoon/*.conf /etc/racoon/remote/
sed -i.bak 's/lifetime time 3600 sec/lifetime time 12 hours/' /etc/racoon/remote/*.conf
sed -i.bak 's/local_address /#   local_address /' /etc/racoon/remote/*.conf
sleep 2
sed -i .bak '$i\
include "/etc/racoon/remote/*.conf" ;
' /etc/racoon/racoon.conf


sleep 2
launchctl stop com.apple.racoon
sleep 5
launchctl start com.apple.racoon
