#!/usr/bin/env ruby
# snap - expand snippets
def snip(pattern, &block)
  @snippets ||= {}
  @snippets[pattern] = block
end

instance_eval File.read(ENV['HOME'] + '/lib/snippets')

ARGF.each do |line|
  @snippets.each_pair do |pattern, block|
    block.call($~) if line =~ pattern
  end
end
